### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by natefourteen** [somnathpanja/youknow#4]
SQLITE_CANTOPEN: unable to open database file
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: SQLITE_CANTOPEN: unable to open database file] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}

**Comment by somnathpanja** [comment]
@natefourteen
Its becase of datafolder was notpresent in side monitor folder.
Anyways im fixing it. Working on it... will update you shortly..

**Comment by somnathpanja** [comment]
@natefourteen
The issue has been fixed. Please re-install Monitor only. Please let me know how it goes!
